'use client';
import { useEffect, useState, type SyntheticEvent } from 'react';
import { AlertTriangle, Pencil, Plus, ShieldCheck, UserRound } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from './ui/dialog';
import { ApiError } from '../lib/auth';
import { atualizarMembro, criarMembro, obterEquipe, type DadosMembro, type Equipe, type MembroEquipe } from '../lib/equipe';

const novo: DadosMembro = { username: '', password: '', first_name: '', last_name: '', email: '', perfil: 'inspetor', is_active: true, pode_administrar_equipe: false };

function MembroForm({ initial, onSaved }: { initial?: MembroEquipe; onSaved: (item: MembroEquipe) => void }) {
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [dados, setDados] = useState<DadosMembro>(novo);
  function changeOpen(next: boolean) { setOpen(next); if (next) { setError(''); setDados(initial ? { first_name: initial.first_name, last_name: initial.last_name, email: initial.email, perfil: initial.perfil, is_active: initial.is_active, pode_administrar_equipe: initial.pode_administrar_equipe } : novo); } }
  function field(key: keyof DadosMembro, value: string | boolean) { setDados(current => ({ ...current, [key]: value })); }
  async function submit(event: SyntheticEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); try { const item = initial ? await atualizarMembro(initial.id, dados) : await criarMembro(dados); onSaved(item); setOpen(false); } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Não foi possível salvar o integrante.'); } finally { setBusy(false); } }
  return <Dialog open={open} onOpenChange={changeOpen}><DialogTrigger className={initial ? 'icon-action' : 'primary'} aria-label={initial ? `Editar ${initial.nome}` : undefined}>{initial ? <Pencil size={17} /> : <><Plus size={17} /> Novo integrante</>}</DialogTrigger><DialogContent className="demand-dialog"><DialogHeader><DialogTitle>{initial ? 'Editar integrante' : 'Novo integrante'}</DialogTitle><DialogDescription>Contas pertencem somente à sua equipe. Alterações em inspetores com demandas ativas são protegidas.</DialogDescription></DialogHeader><form className="demand-form" onSubmit={submit}>{error && <div className="form-error" role="alert"><AlertTriangle size={17} />{error}</div>}{!initial && <><label>Usuário<input required maxLength={150} autoComplete="off" value={dados.username ?? ''} onChange={e => field('username', e.target.value)} /></label><label>Senha inicial<input required minLength={12} type="password" autoComplete="new-password" value={dados.password ?? ''} onChange={e => field('password', e.target.value)} /><small>Use pelo menos 12 caracteres. A senha não será exibida novamente.</small></label></>}<div className="form-row"><label>Nome<input maxLength={150} value={dados.first_name ?? ''} onChange={e => field('first_name', e.target.value)} /></label><label>Sobrenome<input maxLength={150} value={dados.last_name ?? ''} onChange={e => field('last_name', e.target.value)} /></label></div><label>E-mail<input type="email" maxLength={254} value={dados.email ?? ''} onChange={e => field('email', e.target.value)} /></label><label>Papel<select value={dados.perfil} onChange={e => { field('perfil', e.target.value); if (e.target.value === 'inspetor') field('pode_administrar_equipe', false); }}><option value="inspetor">Inspetor</option><option value="gestor">Gestor</option></select></label><label className="check-field"><input type="checkbox" checked={dados.is_active ?? true} onChange={e => field('is_active', e.target.checked)} />Conta ativa</label>{dados.perfil === 'gestor' && <label className="check-field"><input type="checkbox" checked={dados.pode_administrar_equipe ?? false} onChange={e => field('pode_administrar_equipe', e.target.checked)} />Pode administrar a equipe</label>}<div className="form-actions"><button type="button" className="secondary" onClick={() => changeOpen(false)}>Cancelar</button><button className="primary" disabled={busy}>{busy ? 'Salvando…' : 'Salvar integrante'}</button></div></form></DialogContent></Dialog>;
}

export default function EquipeManagement() {
  const [equipe, setEquipe] = useState<Equipe | null>(null); const [error, setError] = useState('');
  useEffect(() => { const controller = new AbortController(); obterEquipe(controller.signal).then(setEquipe).catch(reason => { if (reason.name !== 'AbortError') setError(reason instanceof ApiError ? reason.message : 'Não foi possível carregar a equipe.'); }); return () => controller.abort(); }, []);
  function saved(item: MembroEquipe) { setEquipe(current => current ? { ...current, membros: current.membros.some(member => member.id === item.id) ? current.membros.map(member => member.id === item.id ? item : member) : [...current.membros, item] } : current); }
  if (error) return <section className="team-state" role="alert"><AlertTriangle /><p>{error}</p></section>;
  if (!equipe) return <section className="team-state"><span className="spinner" /><output>Carregando equipe…</output></section>;
  return <section className="team-panel" aria-labelledby="nome-equipe"><div className="team-toolbar"><div><span className="eyebrow">SUA EQUIPE</span><h2 id="nome-equipe">{equipe.nome}</h2><p>{equipe.membros.filter(item => item.is_active).length} integrantes ativos</p></div>{equipe.pode_administrar && <MembroForm onSaved={saved} />}</div><div className="team-list">{equipe.membros.map(member => <article className={`team-member ${member.is_active ? '' : 'is-inactive'}`} key={member.id}><span className="member-avatar"><UserRound /></span><div><h3>{member.nome}</h3><p>@{member.username}{member.email ? ` · ${member.email}` : ''}</p><div className="member-badges"><span className="badge">{member.perfil === 'gestor' ? 'GESTÃO' : 'INSPEÇÃO'}</span>{member.pode_administrar_equipe && <span className="admin-badge"><ShieldCheck size={14} /> Administra a equipe</span>}{!member.is_active && <span className="inactive-badge">Conta inativa</span>}</div></div>{equipe.pode_administrar && <MembroForm initial={member} onSaved={saved} />}</article>)}</div>{!equipe.pode_administrar && <p className="team-note"><ShieldCheck size={17} /> Somente gestores autorizados podem alterar as contas da equipe.</p>}</section>;
}
