'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { AlertTriangle, ArrowRight, CalendarDays, ClipboardList, Megaphone, RotateCcw } from 'lucide-react';
import type { User } from '../lib/auth';
import { obterResumoHome, type ResumoHome } from '../lib/home';

const statusLabel: Record<string, string> = { pendente: 'Pendente', em_andamento: 'Em andamento', aguardando_avaliacao: 'Aguardando avaliação', em_correcao: 'Em correção' };
const day = (value: string) => new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short', timeZone: 'UTC' }).format(new Date(`${value.slice(0, 10)}T12:00:00Z`));
const dateTime = (value: string) => new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit', timeZone: 'America/Fortaleza' }).format(new Date(value));

export default function HomeDashboard({ user }: { user: User }) {
  const [data, setData] = useState<ResumoHome | null>(null); const [error, setError] = useState(false); const [attempt, setAttempt] = useState(0);
  useEffect(() => { const controller = new AbortController(); obterResumoHome(controller.signal).then(setData).catch(reason => { if (reason.name !== 'AbortError') setError(true); }); return () => controller.abort(); }, [attempt]);
  if (error) return <section className="home-state" role="alert"><AlertTriangle /><strong>Não foi possível carregar seu resumo</strong><button className="secondary" onClick={() => { setError(false); setData(null); setAttempt(value => value + 1); }}><RotateCcw size={17} /> Tentar novamente</button></section>;
  if (!data) return <section className="home-state"><span className="spinner" /><output>Organizando seu dia…</output></section>;
  const cards = user.perfil === 'gestor' ? [
    ['atrasadas', 'Demandas vencidas', '?atrasada=true'], ['criticas', 'Demandas críticas', '?critica=true'], ['sem_responsavel', 'Sem responsável', '?sem_responsavel=true'], ['aguardando_avaliacao', 'Aguardando avaliação', '?status=aguardando_avaliacao'],
  ] : [
    ['atrasadas', 'Entregas atrasadas', '?atrasada=true'], ['criticas', 'Demandas críticas', '?critica=true'], ['em_correcao', 'Correções solicitadas', '?status=em_correcao'], ['nao_iniciadas', 'Ainda não iniciadas', '?status=pendente'],
  ];
  return <div className="home-dashboard"><section className="indicator-grid" aria-label="Indicadores do trabalho">{cards.map(([key, label, query]) => <Link href={`/demandas${query}`} className={data.indicadores[key] ? 'indicator-card has-alert' : 'indicator-card'} key={key}><strong>{data.indicadores[key]}</strong><span>{label}</span><ArrowRight size={17} /></Link>)}</section><div className="home-columns"><section className="home-block"><header><div><span className="eyebrow">PRÓXIMOS PRAZOS</span><h2>Demandas prioritárias</h2></div><Link href="/demandas">Ver todas</Link></header>{data.proximas_demandas.length ? <div className="home-items">{data.proximas_demandas.map(item => <Link href={`/demandas/${item.id}`} key={item.id}><span className={`status-dot status-${item.status}`} /><div><strong>{item.titulo}</strong><small>{statusLabel[item.status]}{item.responsavel ? ` · ${item.responsavel.nome}` : ' · Sem responsável'}</small></div><time>{day(item.prazo)}</time></Link>)}</div> : <p className="home-empty"><ClipboardList /> Nenhuma demanda ativa.</p>}</section><section className="home-block"><header><div><span className="eyebrow">AGENDA</span><h2>Próximos 14 dias</h2></div><Link href="/agenda">Abrir agenda</Link></header>{data.proximos_compromissos.length ? <div className="home-items">{data.proximos_compromissos.map(item => <Link href="/agenda" key={item.id}><CalendarDays /><div><strong>{item.titulo}</strong><small>{item.tipo === 'reuniao' ? 'Reunião' : 'Atividade'}</small></div><time>{dateTime(item.inicio)}</time></Link>)}</div> : <p className="home-empty"><CalendarDays /> Nenhum compromisso próximo.</p>}</section></div>{user.perfil === 'gestor' && <section className="home-block workload"><header><div><span className="eyebrow">DISTRIBUIÇÃO</span><h2>Carga ativa por inspetor</h2></div><Link href="/equipe">Ver equipe</Link></header><div className="workload-grid">{data.carga_inspetores?.map(item => <div key={item.id}><span>{item.nome}</span><strong>{item.total}</strong><div><i style={{ width: `${Math.min(100, item.total * 10)}%` }} /></div></div>)}</div></section>}<section className="home-block"><header><div><span className="eyebrow">COMUNICADOS</span><h2>Avisos ativos</h2></div><Link href="/avisos">Ver avisos</Link></header>{data.avisos_ativos.length ? <div className="home-items">{data.avisos_ativos.map(item => <Link href={`/avisos/${item.id}`} key={item.id}><Megaphone /><div><strong>{item.titulo}</strong><small>{item.resumo}</small></div><span className={`notice-tag ${item.categoria}`}>{item.categoria}</span></Link>)}</div> : <p className="home-empty"><Megaphone /> Nenhum aviso ativo.</p>}</section></div>;
}
