# Generated by Django 5.2.17 on 2026-09-06 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('reuniao', 'Reunião'), ('atividade', 'Atividade')], max_length=12)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('referencia_demo', models.CharField(blank=True, editable=False, max_length=60, null=True, unique=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromissos_criados', to=settings.AUTH_USER_MODEL)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromissos', to='usuarios.equipe')),
                ('participantes', models.ManyToManyField(related_name='compromissos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['inicio', 'fim', 'id'],
                'indexes': [models.Index(fields=['equipe', 'inicio', 'fim', 'id'], name='comp_equipe_intervalo'), models.Index(fields=['inicio', 'fim', 'id'], name='comp_intervalo')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='comp_fim_apos_inicio'), models.CheckConstraint(condition=models.Q(('tipo__in', ['reuniao', 'atividade'])), name='comp_tipo_valido')],
            },
        ),
    ]
