# Generated by Django 5.2.17 on 2026-09-06 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.CharField(max_length=300)),
                ('conteudo', models.TextField()),
                ('categoria', models.CharField(choices=[('urgente', 'Urgente'), ('informativo', 'Informativo')], max_length=12)),
                ('publicado_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('referencia_demo', models.CharField(blank=True, editable=False, max_length=60, null=True, unique=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avisos_criados', to=settings.AUTH_USER_MODEL)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avisos', to='usuarios.equipe')),
            ],
            options={
                'ordering': ['categoria', '-publicado_em', '-id'],
                'indexes': [models.Index(fields=['equipe', 'categoria', 'publicado_em', 'id'], name='aviso_equipe_feed')],
                'constraints': [models.CheckConstraint(condition=models.Q(('categoria__in', ['urgente', 'informativo'])), name='aviso_categoria_valida')],
            },
        ),
    ]
