# Generated by Django 5.2.17 on 2026-09-24 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0002_aviso_cancelado_em_aviso_cancelado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lido_em', models.DateTimeField()),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='avisos.aviso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_avisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('aviso', 'usuario'), name='leitura_aviso_usuario_unico')],
            },
        ),
    ]
