# Generated by Django 5.2.17 on 2026-09-16 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_pode_administrar_equipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('gestor', 'Gestor'), ('inspetor', 'Inspetor')], max_length=10)),
                ('pode_administrar', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='usuarios.equipe')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_equipe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('equipe__nome', 'usuario__first_name', 'usuario__last_name', 'id'),
                'constraints': [models.UniqueConstraint(fields=('usuario', 'equipe'), name='vinculo_usuario_equipe_unico'), models.CheckConstraint(condition=models.Q(('pode_administrar', False), ('papel', 'gestor'), _connector='OR'), name='vinculo_admin_gestor')],
            },
        ),
    ]
