# Generated by Django 5.2.17 on 2026-09-05 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandas', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demanda',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.equipe'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandas_atribuidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='demanda',
            index=models.Index(fields=['equipe', 'status', 'prazo', 'id'], name='demanda_equipe_status'),
        ),
        migrations.AddIndex(
            model_name='demanda',
            index=models.Index(fields=['responsavel', 'status', 'prazo', 'id'], name='demanda_resp_status'),
        ),
        migrations.AddIndex(
            model_name='demanda',
            index=models.Index(fields=['equipe', 'critica', 'prazo', 'id'], name='demanda_equipe_critica'),
        ),
        migrations.AddConstraint(
            model_name='demanda',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pendente', 'em_andamento', 'concluida', 'cancelada'])), name='demanda_status_valido'),
        ),
        migrations.AddConstraint(
            model_name='demanda',
            constraint=models.CheckConstraint(condition=models.Q(('prioridade__in', ['baixa', 'media', 'alta'])), name='demanda_prioridade_valida'),
        ),
    ]
