# Generated by Django 5.2.17 on 2026-09-06 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('status_alterado', 'Status alterado'), ('comentario', 'Comentário')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('status_anterior', models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], max_length=20)),
                ('status_novo', models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], max_length=20)),
                ('texto', models.CharField(blank=True, max_length=2000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_demandas', to=settings.AUTH_USER_MODEL)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='demandas.demanda')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['demanda', '-criado_em', '-id'], name='evento_demanda_data')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status_anterior__gt', ''), ('status_novo__gt', ''), ('texto', ''), ('tipo', 'status_alterado')), models.Q(('status_anterior', ''), ('status_novo', ''), ('texto__gt', ''), ('tipo', 'comentario')), _connector='OR'), name='evento_conteudo_por_tipo')],
            },
        ),
    ]
