# Generated by Django 5.2.17 on 2026-09-06 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0003_eventodemanda'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='demanda',
            name='demanda_status_valido',
        ),
        migrations.RemoveConstraint(
            model_name='eventodemanda',
            name='evento_conteudo_por_tipo',
        ),
        migrations.AlterField(
            model_name='demanda',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('aguardando_avaliacao', 'Aguardando avaliação'), ('em_correcao', 'Em correção'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventodemanda',
            name='status_anterior',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('aguardando_avaliacao', 'Aguardando avaliação'), ('em_correcao', 'Em correção'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventodemanda',
            name='status_novo',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('aguardando_avaliacao', 'Aguardando avaliação'), ('em_correcao', 'Em correção'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='demanda',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pendente', 'em_andamento', 'aguardando_avaliacao', 'em_correcao', 'concluida', 'cancelada'])), name='demanda_status_valido'),
        ),
        migrations.AddConstraint(
            model_name='eventodemanda',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status_anterior__gt', ''), ('status_novo__gt', ''), ('tipo', 'status_alterado')), models.Q(('status_anterior', ''), ('status_novo', ''), ('texto__gt', ''), ('tipo', 'comentario')), _connector='OR'), name='evento_conteudo_por_tipo'),
        ),
    ]
