# Generated by Django 5.2.17 on 2026-09-06 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0004_remove_demanda_demanda_status_valido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventodemanda',
            name='evento_conteudo_por_tipo',
        ),
        migrations.AddField(
            model_name='demanda',
            name='origem',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='eventodemanda',
            name='tipo',
            field=models.CharField(choices=[('demanda_criada', 'Demanda criada'), ('demanda_editada', 'Demanda editada'), ('responsavel_alterado', 'Responsável alterado'), ('status_alterado', 'Status alterado'), ('comentario', 'Comentário')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='eventodemanda',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status_anterior__gt', ''), ('status_novo__gt', ''), ('tipo', 'status_alterado')), models.Q(('status_anterior', ''), ('status_novo', ''), ('texto__gt', ''), ('tipo', 'comentario')), models.Q(('status_anterior', ''), ('status_novo', ''), ('texto__gt', ''), ('tipo__in', ['demanda_criada', 'demanda_editada', 'responsavel_alterado'])), _connector='OR'), name='evento_conteudo_por_tipo'),
        ),
    ]
